// <auto-generated />
using System;
using AccountsService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AccountsService.Migrations
{
    [DbContext(typeof(AccountsDbContext))]
    [Migration("20260409120000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountsService.Entities.Agent", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").HasColumnName("idAgent");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("AgentType").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("CreatedBy").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<decimal>("CreditLimitMax").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("bit");
                b.Property<string>("LoginName").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<string>("Name").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int?>("ParentAgentId").HasColumnType("int");
                b.Property<decimal>("WagerLimitMax").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("LoginName").IsUnique().HasDatabaseName("IX_Agent_LoginName");
                b.HasIndex("ParentAgentId");
                b.ToTable("Agent");
            });

            modelBuilder.Entity("AccountsService.Entities.Customer", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").HasColumnName("idCustomer");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AgentId").HasColumnType("int");
                b.Property<string>("AlternateLoginName").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("CreatedBy").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Email").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<bool>("InstantActionEnabled").HasDefaultValue(true).HasColumnType("bit");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("bit");
                b.Property<string>("LoginName").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<string>("OddsFormat").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("Phone").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("Id");
                b.HasIndex("AgentId");
                b.HasIndex("LoginName").IsUnique().HasDatabaseName("IX_Customer_LoginName");
                b.ToTable("Customer");
            });

            modelBuilder.Entity("AccountsService.Entities.CustomerBalance", b =>
            {
                b.Property<int>("CustomerId").HasColumnType("int");
                b.Property<decimal>("CreditLimit").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal>("CurrentBalance").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal>("FreePlayBalance").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal>("FreePlayPendingBalance").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<int>("FreePlayPendingCount").HasColumnType("int");
                b.Property<decimal>("PendingWagerBalance").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<int>("PendingWagerCount").HasColumnType("int");
                b.Property<DateTime?>("TempCreditAdjExpiry").HasColumnType("datetime2");
                b.Property<decimal>("TempCreditAdjustment").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal>("WagerLimit").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.HasKey("CustomerId");
                b.ToTable("CustomerBalance");
            });

            modelBuilder.Entity("AccountsService.Entities.CustomerLimits", b =>
            {
                b.Property<int>("CustomerId").HasColumnType("int");
                b.Property<decimal>("HardCreditLimit").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal>("MaxIfBetWager").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal>("MaxLotteryPick3").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal>("MaxLotteryPick4").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<int>("MaxParlayLegs").HasDefaultValue(8).HasColumnType("int");
                b.Property<decimal>("MaxParlayPayout").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal>("MaxParlayWager").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal>("MaxStraightWager").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal>("MaxTeaserWager").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<int>("MinimumWager").HasDefaultValue(5).HasColumnType("int");
                b.HasKey("CustomerId");
                b.ToTable("CustomerLimits");
            });

            modelBuilder.Entity("AccountsService.Entities.CustomerTransaction", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AgentId").HasColumnType("int");
                b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal>("BalanceAfter").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal>("BalanceBefore").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<string>("Code").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<int>("CustomerId").HasColumnType("int");
                b.Property<string>("Description").HasMaxLength(255).HasColumnType("nvarchar(255)");
                b.Property<string>("EnteredBy").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<bool>("IsCasinoAdjustment").HasColumnType("bit");
                b.Property<bool>("IsVerified").HasColumnType("bit");
                b.Property<string>("PaymentMethod").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Reference").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("TransactionDate").HasColumnType("datetime2");
                b.Property<string>("Type").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
                b.Property<DateTime?>("ValueDate").HasColumnType("datetime2");
                b.Property<DateTime?>("VerifiedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("CustomerId").HasDatabaseName("IX_CustomerTransaction_CustomerId");
                b.HasIndex("TransactionDate").HasDatabaseName("IX_CustomerTransaction_Date");
                b.ToTable("CustomerTransaction");
            });

            modelBuilder.Entity("AccountsService.Entities.Agent", b =>
            {
                b.HasOne("AccountsService.Entities.Agent", "ParentAgent")
                    .WithMany("SubAgents")
                    .HasForeignKey("ParentAgentId")
                    .OnDelete(DeleteBehavior.Restrict);
                b.Navigation("ParentAgent");
            });

            modelBuilder.Entity("AccountsService.Entities.Customer", b =>
            {
                b.HasOne("AccountsService.Entities.Agent", "Agent")
                    .WithMany("Customers")
                    .HasForeignKey("AgentId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Agent");
            });

            modelBuilder.Entity("AccountsService.Entities.CustomerBalance", b =>
            {
                b.HasOne("AccountsService.Entities.Customer", "Customer")
                    .WithOne("Balance")
                    .HasForeignKey("AccountsService.Entities.CustomerBalance", "CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Customer");
            });

            modelBuilder.Entity("AccountsService.Entities.CustomerLimits", b =>
            {
                b.HasOne("AccountsService.Entities.Customer", "Customer")
                    .WithOne("Limits")
                    .HasForeignKey("AccountsService.Entities.CustomerLimits", "CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Customer");
            });

            modelBuilder.Entity("AccountsService.Entities.CustomerTransaction", b =>
            {
                b.HasOne("AccountsService.Entities.Customer", "Customer")
                    .WithMany("Transactions")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Customer");
            });

            modelBuilder.Entity("AccountsService.Entities.Agent", b =>
            {
                b.Navigation("Customers");
                b.Navigation("SubAgents");
            });

            modelBuilder.Entity("AccountsService.Entities.Customer", b =>
            {
                b.Navigation("Balance").IsRequired();
                b.Navigation("Limits").IsRequired();
                b.Navigation("Transactions");
            });
#pragma warning restore 612, 618
        }
    }
}
