// <auto-generated />
using System;
using AlertsService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AlertsService.Migrations
{
    [DbContext(typeof(AlertsDbContext))]
    [Migration("20260409120000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlertsService.Entities.AgentVipCustomer", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AgentVipSettingsId").HasColumnType("int");
                b.Property<int>("CustomerId").HasColumnType("int");
                b.Property<string>("CustomerLoginName").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.HasKey("Id");
                b.HasIndex("AgentVipSettingsId");
                b.ToTable("AgentVipCustomers");
            });

            modelBuilder.Entity("AlertsService.Entities.AgentVipSettings", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AgentId").HasColumnType("int");
                b.Property<string>("NotificationEmail").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("AgentId").IsUnique();
                b.ToTable("AgentVipSettings");
            });

            modelBuilder.Entity("AlertsService.Entities.AlertAttribute", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AlertTicketId").HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Value").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.HasKey("Id");
                b.HasIndex("AlertTicketId");
                b.ToTable("AlertAttributes");
            });

            modelBuilder.Entity("AlertsService.Entities.AlertDetail", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AlertTicketId").HasColumnType("int");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("SportKey").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("Id");
                b.HasIndex("AlertTicketId");
                b.ToTable("AlertDetails");
            });

            modelBuilder.Entity("AlertsService.Entities.AlertDetailAttribute", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AlertDetailId").HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Value").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.HasKey("Id");
                b.HasIndex("AlertDetailId");
                b.ToTable("AlertDetailAttributes");
            });

            modelBuilder.Entity("AlertsService.Entities.AlertTicket", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AgentId").HasColumnType("int");
                b.Property<int>("AlertType").HasColumnType("int");
                b.Property<decimal>("Amount").HasColumnType("decimal(18,2)");
                b.Property<int>("CustomerId").HasColumnType("int");
                b.Property<string>("CustomerLoginName").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTime>("ExpiresAt").HasColumnType("datetime2");
                b.Property<string>("InetWagerNumber").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("InsertedAt").HasColumnType("datetime2");
                b.Property<bool>("IsSharpAction").HasColumnType("bit");
                b.Property<bool>("IsSquareAction").HasColumnType("bit");
                b.Property<bool>("IsVipAlert").HasColumnType("bit");
                b.Property<int>("VipAgentId").HasColumnType("int");
                b.Property<int>("WagerNumber").HasColumnType("int");
                b.Property<int>("WagerType").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("AgentId");
                b.HasIndex("ExpiresAt");
                b.HasIndex("InsertedAt");
                b.ToTable("AlertTickets");
            });

            modelBuilder.Entity("AlertsService.Entities.AgentVipCustomer", b =>
            {
                b.HasOne("AlertsService.Entities.AgentVipSettings", "AgentVipSettings")
                    .WithMany("VipCustomers")
                    .HasForeignKey("AgentVipSettingsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("AgentVipSettings");
            });

            modelBuilder.Entity("AlertsService.Entities.AlertAttribute", b =>
            {
                b.HasOne("AlertsService.Entities.AlertTicket", "AlertTicket")
                    .WithMany("Attributes")
                    .HasForeignKey("AlertTicketId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("AlertTicket");
            });

            modelBuilder.Entity("AlertsService.Entities.AlertDetail", b =>
            {
                b.HasOne("AlertsService.Entities.AlertTicket", "AlertTicket")
                    .WithMany("Details")
                    .HasForeignKey("AlertTicketId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("AlertTicket");
            });

            modelBuilder.Entity("AlertsService.Entities.AlertDetailAttribute", b =>
            {
                b.HasOne("AlertsService.Entities.AlertDetail", "AlertDetail")
                    .WithMany("Attributes")
                    .HasForeignKey("AlertDetailId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("AlertDetail");
            });

            modelBuilder.Entity("AlertsService.Entities.AgentVipSettings", b =>
            {
                b.Navigation("VipCustomers");
            });

            modelBuilder.Entity("AlertsService.Entities.AlertDetail", b =>
            {
                b.Navigation("Attributes");
            });

            modelBuilder.Entity("AlertsService.Entities.AlertTicket", b =>
            {
                b.Navigation("Attributes");
                b.Navigation("Details");
            });
#pragma warning restore 612, 618
        }
    }
}
