// <auto-generated />
using System;
using AdminService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AdminService.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260411000000_AddUsernameToAuditLog")]
    partial class AddUsernameToAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdminService.Entities.ApplicationUser", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("FirstName").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("bit");
                b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime2");
                b.Property<string>("LastName").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("MaxAccessLevel").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("Id");
                b.HasIndex("Email");
                b.HasIndex("Username").IsUnique();
                b.ToTable("ApplicationUsers");
            });

            modelBuilder.Entity("AdminService.Entities.AuditLog", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                b.Property<string>("Action").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("EntityId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("EntityType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("IpAddress").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("NewValues").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("OccurredAt").HasColumnType("datetime2");
                b.Property<string>("OldValues").HasColumnType("nvarchar(max)");
                b.Property<int>("UserId").HasColumnType("int");
                b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.HasIndex("EntityType", "EntityId");
                b.HasIndex("OccurredAt");
                b.HasIndex("UserId");
                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("AdminService.Entities.Permission", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int>("LegacyBitValue").HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.ToTable("Permissions");
            });

            modelBuilder.Entity("AdminService.Entities.Role", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<bool>("IsSystemRole").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.ToTable("Roles");
            });

            modelBuilder.Entity("AdminService.Entities.RolePermission", b =>
            {
                b.Property<int>("RoleId").HasColumnType("int");
                b.Property<int>("PermissionId").HasColumnType("int");
                b.HasKey("RoleId", "PermissionId");
                b.HasIndex("PermissionId");
                b.ToTable("RolePermissions");
            });

            modelBuilder.Entity("AdminService.Entities.SystemConfiguration", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Description").HasColumnType("nvarchar(max)");
                b.Property<bool>("IsEncrypted").HasColumnType("bit");
                b.Property<string>("Key").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.Property<string>("UpdatedBy").HasColumnType("nvarchar(max)");
                b.Property<string>("Value").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("Key").IsUnique();
                b.ToTable("SystemConfigurations");
            });

            modelBuilder.Entity("AdminService.Entities.UserRole", b =>
            {
                b.Property<int>("UserId").HasColumnType("int");
                b.Property<int>("RoleId").HasColumnType("int");
                b.HasKey("UserId", "RoleId");
                b.HasIndex("RoleId");
                b.ToTable("UserRoles");
            });

            modelBuilder.Entity("AdminService.Entities.AuditLog", b =>
            {
                b.HasOne("AdminService.Entities.ApplicationUser", "User")
                    .WithMany("AuditLogs")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("AdminService.Entities.RolePermission", b =>
            {
                b.HasOne("AdminService.Entities.Permission", "Permission")
                    .WithMany("RolePermissions")
                    .HasForeignKey("PermissionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("AdminService.Entities.Role", "Role")
                    .WithMany("RolePermissions")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Permission");
                b.Navigation("Role");
            });

            modelBuilder.Entity("AdminService.Entities.UserRole", b =>
            {
                b.HasOne("AdminService.Entities.ApplicationUser", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("AdminService.Entities.Role", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Role");
                b.Navigation("User");
            });

            modelBuilder.Entity("AdminService.Entities.ApplicationUser", b =>
            {
                b.Navigation("AuditLogs");
                b.Navigation("UserRoles");
            });

            modelBuilder.Entity("AdminService.Entities.Permission", b =>
            {
                b.Navigation("RolePermissions");
            });

            modelBuilder.Entity("AdminService.Entities.Role", b =>
            {
                b.Navigation("RolePermissions");
                b.Navigation("UserRoles");
            });
#pragma warning restore 612, 618
        }
    }
}
