// <auto-generated />
using System;
using AdminService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace AdminService.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    partial class AdminDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdminService.Entities.ApplicationUser", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("FirstName").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("bit");
                b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime2");
                b.Property<string>("LastName").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("MaxAccessLevel").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("Id");
                b.HasIndex("Email");
                b.HasIndex("Username").IsUnique();
                b.ToTable("ApplicationUsers");
            });

            modelBuilder.Entity("AdminService.Entities.AuditLog", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                b.Property<string>("Action").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("EntityId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("EntityType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("IpAddress").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("NewValues").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("OccurredAt").HasColumnType("datetime2");
                b.Property<string>("OldValues").HasColumnType("nvarchar(max)");
                b.Property<int>("UserId").HasColumnType("int");
                b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.HasIndex("EntityType", "EntityId");
                b.HasIndex("OccurredAt");
                b.HasIndex("UserId");
                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("AdminService.Entities.Permission", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int>("LegacyBitValue").HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.ToTable("Permissions");

                b.HasData(
                    new { Id = 1,  Name = "users.view",         Category = "Users",    Description = "View system users",             LegacyBitValue = 0    },
                    new { Id = 2,  Name = "users.create",        Category = "Users",    Description = "Create system users",           LegacyBitValue = 0    },
                    new { Id = 3,  Name = "users.edit",          Category = "Users",    Description = "Edit system users",             LegacyBitValue = 0    },
                    new { Id = 4,  Name = "users.delete",        Category = "Users",    Description = "Delete system users",           LegacyBitValue = 0    },
                    new { Id = 5,  Name = "roles.manage",        Category = "Roles",    Description = "Manage roles and permissions",  LegacyBitValue = 0    },
                    new { Id = 6,  Name = "wagers.view",         Category = "Wagers",   Description = "View wagers",                   LegacyBitValue = 1    },
                    new { Id = 7,  Name = "wagers.create",       Category = "Wagers",   Description = "Create wagers",                 LegacyBitValue = 2    },
                    new { Id = 8,  Name = "wagers.void",         Category = "Wagers",   Description = "Void wagers",                   LegacyBitValue = 4    },
                    new { Id = 9,  Name = "lines.view",          Category = "Lines",    Description = "View betting lines",            LegacyBitValue = 8    },
                    new { Id = 10, Name = "lines.edit",          Category = "Lines",    Description = "Edit betting lines",            LegacyBitValue = 16   },
                    new { Id = 11, Name = "accounts.view",       Category = "Accounts", Description = "View customer accounts",        LegacyBitValue = 32   },
                    new { Id = 12, Name = "accounts.edit",       Category = "Accounts", Description = "Edit customer accounts",        LegacyBitValue = 64   },
                    new { Id = 13, Name = "transactions.create", Category = "Accounts", Description = "Create financial transactions", LegacyBitValue = 128  },
                    new { Id = 14, Name = "reports.view",        Category = "Reports",  Description = "View reports",                  LegacyBitValue = 256  },
                    new { Id = 15, Name = "config.view",         Category = "System",   Description = "View system configuration",     LegacyBitValue = 512  },
                    new { Id = 16, Name = "config.edit",         Category = "System",   Description = "Edit system configuration",     LegacyBitValue = 1024 },
                    new { Id = 17, Name = "audit.view",          Category = "System",   Description = "View audit logs",               LegacyBitValue = 2048 });
            });

            modelBuilder.Entity("AdminService.Entities.Role", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<bool>("IsSystemRole").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.ToTable("Roles");

                b.HasData(
                    new { Id = 1, Name = "SuperAdmin",  Description = "Full system access",                          IsActive = true, IsSystemRole = true  },
                    new { Id = 2, Name = "Admin",       Description = "Administrative access",                       IsActive = true, IsSystemRole = true  },
                    new { Id = 3, Name = "Supervisor",  Description = "Supervisory access — view all, limited edit", IsActive = true, IsSystemRole = false },
                    new { Id = 4, Name = "LinesMaker",  Description = "Manage betting lines and odds",               IsActive = true, IsSystemRole = false },
                    new { Id = 5, Name = "Cashier",     Description = "Process transactions",                        IsActive = true, IsSystemRole = false },
                    new { Id = 6, Name = "ReadOnly",    Description = "View-only access",                            IsActive = true, IsSystemRole = false });
            });

            modelBuilder.Entity("AdminService.Entities.RolePermission", b =>
            {
                b.Property<int>("RoleId").HasColumnType("int");
                b.Property<int>("PermissionId").HasColumnType("int");
                b.HasKey("RoleId", "PermissionId");
                b.HasIndex("PermissionId");
                b.ToTable("RolePermissions");
            });

            modelBuilder.Entity("AdminService.Entities.SystemConfiguration", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Description").HasColumnType("nvarchar(max)");
                b.Property<bool>("IsEncrypted").HasColumnType("bit");
                b.Property<string>("Key").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.Property<string>("UpdatedBy").HasColumnType("nvarchar(max)");
                b.Property<string>("Value").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("Key").IsUnique();
                b.ToTable("SystemConfigurations");
            });

            modelBuilder.Entity("AdminService.Entities.UserRole", b =>
            {
                b.Property<int>("UserId").HasColumnType("int");
                b.Property<int>("RoleId").HasColumnType("int");
                b.Property<DateTime>("AssignedAt").HasColumnType("datetime2");
                b.Property<int>("AssignedByUserId").HasColumnType("int");
                b.HasKey("UserId", "RoleId");
                b.HasIndex("RoleId");
                b.ToTable("UserRoles");
            });

            modelBuilder.Entity("AdminService.Entities.AuditLog", b =>
            {
                b.HasOne("AdminService.Entities.ApplicationUser", "User")
                    .WithMany("AuditLogs")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("AdminService.Entities.RolePermission", b =>
            {
                b.HasOne("AdminService.Entities.Permission", "Permission")
                    .WithMany("RolePermissions")
                    .HasForeignKey("PermissionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("AdminService.Entities.Role", "Role")
                    .WithMany("RolePermissions")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Permission");
                b.Navigation("Role");
            });

            modelBuilder.Entity("AdminService.Entities.UserRole", b =>
            {
                b.HasOne("AdminService.Entities.ApplicationUser", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("AdminService.Entities.Role", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Role");
                b.Navigation("User");
            });

            modelBuilder.Entity("AdminService.Entities.ApplicationUser", b =>
            {
                b.Navigation("AuditLogs");
                b.Navigation("UserRoles");
            });

            modelBuilder.Entity("AdminService.Entities.Permission", b =>
            {
                b.Navigation("RolePermissions");
            });

            modelBuilder.Entity("AdminService.Entities.Role", b =>
            {
                b.Navigation("RolePermissions");
                b.Navigation("UserRoles");
            });
#pragma warning restore 612, 618
        }
    }
}
