// <auto-generated />
using System;
using AuthService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthService.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260409120000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Entities.ApplicationUser", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("CreatedBy").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int?>("DomainEntityId").HasColumnType("int");
                b.Property<string>("Email").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("bit");
                b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime2");
                b.Property<string>("LoginName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("MaxLevel").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<int>("UserType").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("LoginName").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("AuthService.Entities.Permission", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.ToTable("Permissions");
            });

            modelBuilder.Entity("AuthService.Entities.RefreshToken", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("CreatedByIp").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("ExpiresAt").HasColumnType("datetime2");
                b.Property<bool>("IsRevoked").HasColumnType("bit");
                b.Property<string>("ReplacedByTokenHash").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("RevokedReason").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("TokenHash").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("TokenHash");
                b.HasIndex("UserId", "IsRevoked");
                b.ToTable("RefreshTokens");
            });

            modelBuilder.Entity("AuthService.Entities.Role", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("CreatedBy").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.ToTable("Roles");
            });

            modelBuilder.Entity("AuthService.Entities.RolePermission", b =>
            {
                b.Property<int>("RoleId").HasColumnType("int");
                b.Property<int>("PermissionId").HasColumnType("int");
                b.HasKey("RoleId", "PermissionId");
                b.HasIndex("PermissionId");
                b.ToTable("RolePermissions");
            });

            modelBuilder.Entity("AuthService.Entities.UserRole", b =>
            {
                b.Property<int>("UserId").HasColumnType("int");
                b.Property<int>("RoleId").HasColumnType("int");
                b.Property<DateTime>("AssignedAt").HasColumnType("datetime2");
                b.Property<string>("AssignedBy").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("UserId", "RoleId");
                b.HasIndex("RoleId");
                b.ToTable("UserRoles");
            });

            modelBuilder.Entity("AuthService.Entities.RefreshToken", b =>
            {
                b.HasOne("AuthService.Entities.ApplicationUser", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("AuthService.Entities.RolePermission", b =>
            {
                b.HasOne("AuthService.Entities.Permission", "Permission")
                    .WithMany("RolePermissions")
                    .HasForeignKey("PermissionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("AuthService.Entities.Role", "Role")
                    .WithMany("RolePermissions")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Permission");
                b.Navigation("Role");
            });

            modelBuilder.Entity("AuthService.Entities.UserRole", b =>
            {
                b.HasOne("AuthService.Entities.Role", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("AuthService.Entities.ApplicationUser", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Role");
                b.Navigation("User");
            });

            modelBuilder.Entity("AuthService.Entities.ApplicationUser", b =>
            {
                b.Navigation("RefreshTokens");
                b.Navigation("UserRoles");
            });

            modelBuilder.Entity("AuthService.Entities.Permission", b =>
            {
                b.Navigation("RolePermissions");
            });

            modelBuilder.Entity("AuthService.Entities.Role", b =>
            {
                b.Navigation("RolePermissions");
                b.Navigation("UserRoles");
            });
#pragma warning restore 612, 618
        }
    }
}
