// <auto-generated />
using System;
using CasinoService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CasinoService.Migrations
{
    [DbContext(typeof(CasinoDbContext))]
    [Migration("20260414000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasinoService.Entities.CasinoPlayer", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("CasinoId").HasColumnType("int").HasDefaultValue(2);
                b.Property<string>("CustomerId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("ExternalPlayerId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Nickname").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("RegisteredAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("CustomerId", "CasinoId").IsUnique();
                b.ToTable("CasinoPlayers");
            });

            modelBuilder.Entity("CasinoService.Entities.CasinoTransaction", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<int>("CasinoPlayerId").HasColumnType("int");
                b.Property<DateTime?>("CompletedAt").HasColumnType("datetime2");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<int>("DocumentNumber").HasColumnType("int");
                b.Property<string>("RemoteReference").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("TransferReference").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("TransactionType").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("CasinoPlayerId");
                b.HasIndex("DocumentNumber").IsUnique();
                b.ToTable("CasinoTransactions");
            });

            modelBuilder.Entity("CasinoService.Entities.CasinoTransaction", b =>
            {
                b.HasOne("CasinoService.Entities.CasinoPlayer", "Player")
                    .WithMany("Transactions")
                    .HasForeignKey("CasinoPlayerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Player");
            });

            modelBuilder.Entity("CasinoService.Entities.CasinoPlayer", b =>
            {
                b.Navigation("Transactions");
            });
#pragma warning restore 612, 618
        }
    }
}
