// <auto-generated />
using System;
using BettingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BettingService.Migrations
{
    [DbContext(typeof(BettingDbContext))]
    [Migration("20260409120000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cog.Domain.Entities.Agent", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AgentType").HasColumnType("int");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Email").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("bit");
                b.Property<string>("LoginName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<int?>("ParentAgentId").HasColumnType("int");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("LoginName").IsUnique();
                b.HasIndex("ParentAgentId");
                b.ToTable("Agents");
            });

            modelBuilder.Entity("Cog.Domain.Entities.AgentPermission", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AgentId").HasColumnType("int");
                b.Property<bool>("IsGranted").HasDefaultValue(true).HasColumnType("bit");
                b.Property<string>("PermissionKey").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.HasIndex("AgentId");
                b.ToTable("AgentPermissions");
            });

            modelBuilder.Entity("Cog.Domain.Entities.AuditLog", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                b.Property<string>("Action").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("EntityId").HasColumnType("int");
                b.Property<string>("EntityType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("IpAddress").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("NewValues").HasColumnType("nvarchar(max)");
                b.Property<string>("OldValues").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("PerformedAt").HasColumnType("datetime2");
                b.Property<string>("PerformedBy").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.HasIndex("EntityType", "EntityId");
                b.HasIndex("PerformedAt");
                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("Cog.Domain.Entities.Customer", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AgentId").HasColumnType("int");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Email").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("IsVip").HasColumnType("bit");
                b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("LoginName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("Phone").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("AgentId");
                b.HasIndex("LoginName").IsUnique();
                b.ToTable("Customers");
            });

            modelBuilder.Entity("Cog.Domain.Entities.CustomerBalance", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<decimal>("Balance").HasColumnType("decimal(18,2)");
                b.Property<decimal>("CasinoBalance").HasColumnType("decimal(18,2)");
                b.Property<decimal>("CreditLimit").HasColumnType("decimal(18,2)");
                b.Property<int>("CustomerId").HasColumnType("int");
                b.Property<decimal>("FreePlaysBalance").HasColumnType("decimal(18,2)");
                b.Property<DateTime>("LastUpdated").HasColumnType("datetime2");
                b.Property<decimal>("TemporaryCreditLimit").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("CustomerId").IsUnique();
                b.ToTable("CustomerBalances");
            });

            modelBuilder.Entity("Cog.Domain.Entities.CustomerLimits", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<bool>("AllowCasino").HasDefaultValue(true).HasColumnType("bit");
                b.Property<bool>("AllowIfBet").HasDefaultValue(true).HasColumnType("bit");
                b.Property<bool>("AllowLottery").HasDefaultValue(true).HasColumnType("bit");
                b.Property<bool>("AllowParlay").HasDefaultValue(true).HasColumnType("bit");
                b.Property<bool>("AllowReverse").HasDefaultValue(true).HasColumnType("bit");
                b.Property<bool>("AllowStraight").HasDefaultValue(true).HasColumnType("bit");
                b.Property<bool>("AllowTeaser").HasDefaultValue(true).HasColumnType("bit");
                b.Property<int>("CustomerId").HasColumnType("int");
                b.Property<decimal>("MaxWagerIfBet").HasColumnType("decimal(18,2)");
                b.Property<decimal>("MaxWagerParlay").HasColumnType("decimal(18,2)");
                b.Property<decimal>("MaxWagerReverse").HasColumnType("decimal(18,2)");
                b.Property<decimal>("MaxWagerStraight").HasColumnType("decimal(18,2)");
                b.Property<decimal>("MaxWagerTeaser").HasColumnType("decimal(18,2)");
                b.Property<decimal>("MaxWinPerTicket").HasColumnType("decimal(18,2)");
                b.Property<decimal>("MinWager").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("CustomerId").IsUnique();
                b.ToTable("CustomerLimits");
            });

            modelBuilder.Entity("Cog.Domain.Entities.Game", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("AwayTeam").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("GameDate").HasColumnType("datetime2");
                b.Property<string>("HomeTeam").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("RotationNumber").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<int>("SportTypeId").HasColumnType("int");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("GameDate");
                b.HasIndex("SportTypeId");
                b.ToTable("Games");
            });

            modelBuilder.Entity("Cog.Domain.Entities.GamePeriod", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("GameId").HasColumnType("int");
                b.Property<string>("PeriodDescription").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("PeriodNumber").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("GameId");
                b.ToTable("GamePeriods");
            });

            modelBuilder.Entity("Cog.Domain.Entities.LineSet", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<decimal?>("AwayMoneyLine").HasColumnType("decimal(8,2)");
                b.Property<int>("GamePeriodId").HasColumnType("int");
                b.Property<decimal?>("HomeMoneyLine").HasColumnType("decimal(8,2)");
                b.Property<DateTime>("LastModified").HasColumnType("datetime2");
                b.Property<string>("ModifiedBy").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("OfferingMoneyLine").HasDefaultValue(true).HasColumnType("bit");
                b.Property<bool>("OfferingSpread").HasDefaultValue(true).HasColumnType("bit");
                b.Property<bool>("OfferingTotal").HasDefaultValue(true).HasColumnType("bit");
                b.Property<decimal?>("OverJuice").HasColumnType("decimal(6,2)");
                b.Property<decimal?>("Spread").HasColumnType("decimal(6,2)");
                b.Property<decimal?>("SpreadJuice").HasColumnType("decimal(6,2)");
                b.Property<decimal?>("Total").HasColumnType("decimal(6,2)");
                b.Property<decimal?>("UnderJuice").HasColumnType("decimal(6,2)");
                b.HasKey("Id");
                b.HasIndex("GamePeriodId").IsUnique();
                b.ToTable("LineSets");
            });

            modelBuilder.Entity("Cog.Domain.Entities.LineShade", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AgentId").HasColumnType("int");
                b.Property<decimal?>("AwayMoneyLineAdjustment").HasColumnType("decimal(8,2)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<decimal?>("HomeMoneyLineAdjustment").HasColumnType("decimal(8,2)");
                b.Property<int>("LineSetId").HasColumnType("int");
                b.Property<decimal?>("SpreadAdjustment").HasColumnType("decimal(6,2)");
                b.Property<decimal?>("TotalAdjustment").HasColumnType("decimal(6,2)");
                b.HasKey("Id");
                b.HasIndex("AgentId");
                b.HasIndex("LineSetId");
                b.ToTable("LineShades");
            });

            modelBuilder.Entity("Cog.Domain.Entities.SportType", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Code").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<int>("DisplayOrder").HasColumnType("int");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.HasIndex("Code").IsUnique();
                b.ToTable("SportTypes");
            });

            modelBuilder.Entity("Cog.Domain.Entities.Transaction", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<decimal>("Amount").HasColumnType("decimal(18,2)");
                b.Property<decimal>("BalanceAfter").HasColumnType("decimal(18,2)");
                b.Property<decimal>("BalanceBefore").HasColumnType("decimal(18,2)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("CreatedBy").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("CustomerId").HasColumnType("int");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int?>("RelatedWagerId").HasColumnType("int");
                b.Property<int>("TransactionType").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("CreatedAt");
                b.HasIndex("CustomerId");
                b.HasIndex("RelatedWagerId");
                b.ToTable("Transactions");
            });

            modelBuilder.Entity("Cog.Domain.Entities.Wager", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<decimal?>("ActualPayout").HasColumnType("decimal(18,2)");
                b.Property<int>("AgentId").HasColumnType("int");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<int>("CustomerId").HasColumnType("int");
                b.Property<DateTime?>("GradedAt").HasColumnType("datetime2");
                b.Property<string>("GradedBy").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("IdempotencyKey").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<decimal>("RiskAmount").HasColumnType("decimal(18,2)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("TicketNumber").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<int>("WagerType").HasColumnType("int");
                b.Property<decimal>("WinAmount").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("CreatedAt");
                b.HasIndex("CustomerId");
                b.HasIndex("IdempotencyKey").IsUnique().HasFilter("[IdempotencyKey] IS NOT NULL");
                b.ToTable("Wagers");
            });

            modelBuilder.Entity("Cog.Domain.Entities.WagerItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int?>("AwayScore").HasColumnType("int");
                b.Property<int>("GamePeriodId").HasColumnType("int");
                b.Property<int?>("HomeScore").HasColumnType("int");
                b.Property<int>("ItemType").HasColumnType("int");
                b.Property<decimal>("LineAtTimeOfWager").HasColumnType("decimal(8,2)");
                b.Property<int>("Side").HasColumnType("int");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<int>("WagerId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("GamePeriodId");
                b.HasIndex("WagerId");
                b.ToTable("WagerItems");
            });

            // ── Relationships ─────────────────────────────────────────────────────

            modelBuilder.Entity("Cog.Domain.Entities.Agent", b =>
            {
                b.HasOne("Cog.Domain.Entities.Agent", "ParentAgent")
                    .WithMany("SubAgents")
                    .HasForeignKey("ParentAgentId")
                    .OnDelete(DeleteBehavior.Restrict);
                b.Navigation("ParentAgent");
            });

            modelBuilder.Entity("Cog.Domain.Entities.AgentPermission", b =>
            {
                b.HasOne("Cog.Domain.Entities.Agent", "Agent")
                    .WithMany("Permissions")
                    .HasForeignKey("AgentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Agent");
            });

            modelBuilder.Entity("Cog.Domain.Entities.Customer", b =>
            {
                b.HasOne("Cog.Domain.Entities.Agent", "Agent")
                    .WithMany("Customers")
                    .HasForeignKey("AgentId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Agent");
            });

            modelBuilder.Entity("Cog.Domain.Entities.CustomerBalance", b =>
            {
                b.HasOne("Cog.Domain.Entities.Customer", "Customer")
                    .WithOne("Balance")
                    .HasForeignKey("Cog.Domain.Entities.CustomerBalance", "CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Customer");
            });

            modelBuilder.Entity("Cog.Domain.Entities.CustomerLimits", b =>
            {
                b.HasOne("Cog.Domain.Entities.Customer", "Customer")
                    .WithOne("Limits")
                    .HasForeignKey("Cog.Domain.Entities.CustomerLimits", "CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Customer");
            });

            modelBuilder.Entity("Cog.Domain.Entities.Game", b =>
            {
                b.HasOne("Cog.Domain.Entities.SportType", "SportType")
                    .WithMany("Games")
                    .HasForeignKey("SportTypeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("SportType");
            });

            modelBuilder.Entity("Cog.Domain.Entities.GamePeriod", b =>
            {
                b.HasOne("Cog.Domain.Entities.Game", "Game")
                    .WithMany("Periods")
                    .HasForeignKey("GameId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Game");
            });

            modelBuilder.Entity("Cog.Domain.Entities.LineSet", b =>
            {
                b.HasOne("Cog.Domain.Entities.GamePeriod", "GamePeriod")
                    .WithOne("LineSet")
                    .HasForeignKey("Cog.Domain.Entities.LineSet", "GamePeriodId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("GamePeriod");
            });

            modelBuilder.Entity("Cog.Domain.Entities.LineShade", b =>
            {
                b.HasOne("Cog.Domain.Entities.Agent", "Agent")
                    .WithMany()
                    .HasForeignKey("AgentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("Cog.Domain.Entities.LineSet", "LineSet")
                    .WithMany("Shades")
                    .HasForeignKey("LineSetId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Agent");
                b.Navigation("LineSet");
            });

            modelBuilder.Entity("Cog.Domain.Entities.Transaction", b =>
            {
                b.HasOne("Cog.Domain.Entities.Customer", "Customer")
                    .WithMany("Transactions")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("Cog.Domain.Entities.Wager", "RelatedWager")
                    .WithMany()
                    .HasForeignKey("RelatedWagerId")
                    .OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Customer");
                b.Navigation("RelatedWager");
            });

            modelBuilder.Entity("Cog.Domain.Entities.Wager", b =>
            {
                b.HasOne("Cog.Domain.Entities.Customer", "Customer")
                    .WithMany("Wagers")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Customer");
            });

            modelBuilder.Entity("Cog.Domain.Entities.WagerItem", b =>
            {
                b.HasOne("Cog.Domain.Entities.GamePeriod", "GamePeriod")
                    .WithMany()
                    .HasForeignKey("GamePeriodId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("Cog.Domain.Entities.Wager", "Wager")
                    .WithMany("Items")
                    .HasForeignKey("WagerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("GamePeriod");
                b.Navigation("Wager");
            });

            // ── Navigations ───────────────────────────────────────────────────────

            modelBuilder.Entity("Cog.Domain.Entities.Agent", b =>
            {
                b.Navigation("Customers");
                b.Navigation("Permissions");
                b.Navigation("SubAgents");
            });

            modelBuilder.Entity("Cog.Domain.Entities.Customer", b =>
            {
                b.Navigation("Balance");
                b.Navigation("Limits");
                b.Navigation("Transactions");
                b.Navigation("Wagers");
            });

            modelBuilder.Entity("Cog.Domain.Entities.Game", b =>
            {
                b.Navigation("Periods");
            });

            modelBuilder.Entity("Cog.Domain.Entities.GamePeriod", b =>
            {
                b.Navigation("LineSet");
            });

            modelBuilder.Entity("Cog.Domain.Entities.LineSet", b =>
            {
                b.Navigation("Shades");
            });

            modelBuilder.Entity("Cog.Domain.Entities.SportType", b =>
            {
                b.Navigation("Games");
            });

            modelBuilder.Entity("Cog.Domain.Entities.Wager", b =>
            {
                b.Navigation("Items");
            });
#pragma warning restore 612, 618
        }
    }
}
